spring:
  datasource:
    url: "jdbc:mysql://localhost:${MYSQL_PORT_AUTH}/${MYSQL_DATABASE_AUTH}"
    username: ${MYSQL_USER_AUTH}
    password: ${MYSQL_PASSWORD_AUTH}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
