spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_ORDER_PORT}/${POSTGRES_ORDER_DB}
    username: ${POSTGRES_ORDER_USER}
    password: ${POSTGRES_ORDER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
